version: '3'

services:
    gateway2:
        container_name: gateway2
        restart: always
        build: ./microservicios/gateway2
        ports:
            - "7000:7000"

    characters:
        container_name: characters
        restart: always
        build: ./microservicios/characters
        ports:
            - "7001:7001"

    films:
        container_name: films
        restart: always
        build: ./microservicios/films
        ports:
            - "7002:7002"

    planets:
        container_name: planets
        restart: always
        build: ./microservicios/planets
        ports:
            - "7003:7003"

    db:
        container_name: db
        restart: always
        build:  ./microservicios/db
        ports:
            - "7004:7004"

    client:
        container_name: client
        entrypoint: /bin/bash
        restart: always
        build: ./client
        ports:
            - "5173:5173"